// -----------------------------------------------------------------------------
// aegis_pkg — shared constants for BaselineNoC and AegisNoC.
//
// Synthesis-safe: localparams only (no functions with side effects, no types
// that tools disagree on). Every RTL module imports this package.
//
// Logical flit format (32 bits):
//   [31:30] destination X
//   [29:28] destination Y
//   [27:0]  payload
//
// Coordinate orientation (one canonical convention for the whole project):
//   X increases toward EAST, Y increases toward NORTH.
// -----------------------------------------------------------------------------
package aegis_pkg;

  // ---- Ports -----------------------------------------------------------------
  localparam int NUM_PORTS = 5;
  localparam int PORT_IDX_W = 3;         // bits needed to index 5 ports

  localparam logic [PORT_IDX_W-1:0] PORT_N = 3'd0;
  localparam logic [PORT_IDX_W-1:0] PORT_S = 3'd1;
  localparam logic [PORT_IDX_W-1:0] PORT_E = 3'd2;
  localparam logic [PORT_IDX_W-1:0] PORT_W = 3'd3;
  localparam logic [PORT_IDX_W-1:0] PORT_L = 3'd4;

  // ---- Flit ------------------------------------------------------------------
  localparam int COORD_W   = 2;
  localparam int FLIT_W    = 32;
  // Field boundaries (MSB constants document the format; only LSBs are used by RTL).
  /* verilator lint_off UNUSEDPARAM */
  localparam int PAYLOAD_W = FLIT_W - 2*COORD_W;  // 28
  localparam int DX_MSB    = FLIT_W - 1;          // 31
  localparam int DY_MSB    = FLIT_W - COORD_W - 1;// 29
  /* verilator lint_on UNUSEDPARAM */
  localparam int DX_LSB    = FLIT_W - COORD_W;    // 30
  localparam int DY_LSB    = FLIT_W - 2*COORD_W;  // 28

  // ---- Buffering -------------------------------------------------------------
  localparam int FIFO_DEPTH = 4;

  // ---- SECDED ECC ------------------------------------------------------------
  // Protected data width m = 32 (the whole logical flit, header included).
  // Hamming parity bits r = smallest r with 2^r >= m + r + 1  ->  r = 6
  //   (r = 5 fails: 32 < 38;  r = 6 works: 64 >= 39).
  // Plus 1 overall parity bit -> SECDED, total codeword n = 32 + 6 + 1 = 39.
  //
  // Hamming positions 1..38: parity bits sit at the powers of two
  // (1,2,4,8,16,32); data bits d[0..31] fill the remaining positions in order:
  //   d0..d3  -> 3,5,6,7          d4..d10  -> 9..15
  //   d11..d25 -> 17..31          d26..d31 -> 33..38
  // Parity bit j covers every position with bit j set. ECC_Mj below is that
  // coverage expressed over the data bits: ECC_Mj[i] = bit j of pos(d_i).
  // (Generated by script; checked against an independent positional model in
  // tb/ecc_ref_model.svh and formally in formal/ecc_properties.sv.)
  //
  // Physical (transmitted/stored) codeword layout, systematic:
  //   [38]    overall parity P  (even parity over all 39 bits)
  //   [37:32] Hamming parity p[5:0]  (p[j] = check bit for position 2^j)
  //   [31:0]  logical flit data
  //
  // Syndrome s[5:0] = recomputed parity XOR received parity; overall check
  // q = XOR of all 39 received bits.
  //   q=0, s=0        : no error
  //   q=1, s=0        : overall parity bit [38] flipped      -> corrected (data intact)
  //   q=1, s=2^j      : check bit p[j] flipped               -> corrected (data intact)
  //   q=1, s=pos(d_i) : data bit d_i flipped                 -> corrected (d_i inverted)
  //   q=1, s>38       : odd multi-bit error (no such single position) -> uncorrectable
  //   q=0, s!=0       : double-bit error                     -> uncorrectable
  // (Unused by baseline_noc by design: waive Verilator's unused-parameter lint.)
  /* verilator lint_off UNUSEDPARAM */
  localparam int ECC_DATA_W = 32;
  localparam int ECC_PAR_W  = 6;
  localparam int ECC_CW_W   = ECC_DATA_W + ECC_PAR_W + 1;   // 39
  localparam int ECC_MAX_POS = ECC_DATA_W + ECC_PAR_W;      // 38

  localparam logic [31:0] ECC_M0 = 32'h56AA_AD5B;
  localparam logic [31:0] ECC_M1 = 32'h9B33_366D;
  localparam logic [31:0] ECC_M2 = 32'hE3C3_C78E;
  localparam logic [31:0] ECC_M3 = 32'h03FC_07F0;
  localparam logic [31:0] ECC_M4 = 32'h03FF_F800;
  localparam logic [31:0] ECC_M5 = 32'hFC00_0000;
  /* verilator lint_on UNUSEDPARAM */

endpackage
